license = "MIT"
modLoader = "lowcodefml"
loaderVersion = "[47,)"

[dependencies]

	[[dependencies.ad_astra_planet_screen_expanded]]
		versionRange = "[1.0.0,)"
		side = "BOTH"
		ordering = "NONE"
		mandatory = true
		modId = "kube_packages"

[[mods]]
	displayName = "Ad Astra: Planet Screen Expanded"
	description = "A scripted expansion of Ad Astra's planet screen."
	version = "1.0"
	modId = "ad_astra_planet_screen_expanded"
	authors = "LittleWindow"
	logoFile = "icon.png"

